### ISSUE TITLE
Unrecognized option or bad number of args for: '--no-auth-warning'

### ISSUE THREAD

**Issue by lizhede** [eyjian/redis-tools#1]
redis 版本3.2.11 使用 show_redis_map.sh 
报错：Unrecognized option or bad number of args for: '--no-auth-warning'
我去掉--no-auth-warning就好使了，是redis版本问题么？

**Comment by eyjian** [comment]
是redis版本问题，低版本不支持“--no-auth-warning”，建议上高版本，推荐5.0.5版本，这个版本稳定很长时间了。 
------------------
CSDN博客：https://blog.csdn.net/aquester
ChinaUnix博客：http://aquester.blog.chinaunix.net
开源创作：https://github.com/eyjian/
 

 




------------------ 原始邮件 ------------------
发件人: "lizhede"<notifications@github.com>; 
发送时间: 2019年8月23日(星期五) 上午9:54
收件人: "eyjian/redis-tools"<redis-tools@noreply.github.com>; 
抄送: "Subscribed"<subscribed@noreply.github.com>; 
主题: [eyjian/redis-tools] Unrecognized option or bad number of args for:'--no-auth-warning' (#1)




redis 版本3.2.11 使用 show_redis_map.sh
 报错：Unrecognized option or bad number of args for: '--no-auth-warning'
 我去掉--no-auth-warning就好使了，是redis版本问题么？

**Comment by lizhede** [comment]
好的，谢谢！
